### PR TITLE
Replace grunt with gulp setup

### PR DESCRIPTION
**Pull request by gabrielpoca**
The setup in use is more advanced and easier to customize. The main
reason for this change came from the frustration of adding
$templaceCache to the previous setup.

### CODE REVIEW

**Comment by gabrielpoca** [comment]
@joaojusto bump

**Comment by joaojusto** [comment]
:+1:  looks good

**Comment by gabrielpoca** [comment]
@joaojusto can you please test it? Download to you computer and run it.

**Comment by joaojusto** [comment]
@gabrielpoca just tested it, working fine :shipit:

**Pull request merged**
